# Generated by Django 5.0.1 on 2024-02-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_ingredientuser_options_ingredientuser_test_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngredientUser',
        ),
    ]
