# Generated by Django 5.0.1 on 2024-02-20 12:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0005_alter_recipe_ingredients_and_more'),
        ('users', '0003_delete_ingredientuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecords',
            options={'verbose_name': 'Рекорд пользователя', 'verbose_name_plural': 'Рекорды пользователей'},
        ),
        migrations.AlterModelOptions(
            name='useringredientreview',
            options={'verbose_name': 'Комментарий на ингредиент', 'verbose_name_plural': 'Комментарии на игредиенты'},
        ),
        migrations.AlterModelOptions(
            name='userrecipereview',
            options={'verbose_name': 'Комментарий на рецепт', 'verbose_name_plural': 'Комментарии на рецепты'},
        ),
        migrations.AddField(
            model_name='useringredientreview',
            name='subcomments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.useringredientreview', verbose_name='Ответ на комментарий ингредиента'),
        ),
        migrations.AddField(
            model_name='userrecipereview',
            name='subcomments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userrecipereview', verbose_name='Ответ на комментарий рецепта'),
        ),
        migrations.AlterField(
            model_name='ingredientrecords',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество использований'),
        ),
        migrations.AlterField(
            model_name='ingredientrecords',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IngredientRecord', to='cooking.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='ingredientrecords',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserRecord', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='useringredientreview',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='useringredientreview',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cooking.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='useringredientreview',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='useringredientreview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userrecipereview',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='userrecipereview',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='userrecipereview',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cooking.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='userrecipereview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
