# Generated by Django 5.0.1 on 2024-02-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_ingredientrecords_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useringredientreview',
            old_name='subcomments',
            new_name='subcomment',
        ),
        migrations.RenameField(
            model_name='userrecipereview',
            old_name='subcomments',
            new_name='subcomment',
        ),
    ]
