# Generated by Django 5.0.1 on 2024-02-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_useringredientreview_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useringredientreview',
            name='subcomment',
        ),
        migrations.RemoveField(
            model_name='userrecipereview',
            name='subcomment',
        ),
        migrations.AlterField(
            model_name='useringredientreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='userrecipereview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Оценка'),
        ),
    ]
