# Generated by Django 5.0.1 on 2024-02-10 09:39

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название блюда')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Имя ингредиента')),
                ('description', models.TextField(verbose_name='Описание продукта')),
                ('image', models.ImageField(upload_to='static/images/%Y/%m/%d/', verbose_name='Картинка ингредиента')),
                ('carbs', models.FloatField(default=1, verbose_name='Углеводы')),
                ('fats', models.FloatField(default=1, verbose_name='Жиры')),
                ('protein', models.FloatField(default=1, verbose_name='Белки')),
                ('calories', models.FloatField(default=1, verbose_name='Калорийность')),
                ('vegan', models.BooleanField(verbose_name='Вегетарианская')),
                ('halal', models.BooleanField(verbose_name='Халяль')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название рецепта')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('usage', models.PositiveIntegerField(default=0, verbose_name='Количество использований')),
                ('image', models.ImageField(upload_to='static/images/%Y/%m/%d/', verbose_name='Картинка рецепта')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(choices=[('мл', 'Миллилитры'), ('г', 'Граммы'), ('ст.л.', 'Столовые ложки'), ('шт', 'Штуки')], max_length=255, verbose_name='Единицы измерения')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Ингредиент рецепта',
                'verbose_name_plural': 'Ингредиенты рецептов',
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Номер шага')),
                ('title', models.CharField(max_length=255, verbose_name='Название шага')),
                ('description', models.TextField(null=True, verbose_name='Описание шага')),
                ('image', models.ImageField(upload_to='static/images/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Шаг готовки',
                'verbose_name_plural': 'Шаги готовки',
            },
        ),
        migrations.CreateModel(
            name='RequestIngredient',
            fields=[
                ('ingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cooking.ingredient')),
                ('is_active', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Заявка в ингредиенты',
                'verbose_name_plural': 'Заявки в ингредиенты',
            },
            bases=('cooking.ingredient',),
        ),
    ]
