# Generated by Django 5.0.1 on 2024-02-03 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dish_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='cooking.dish', verbose_name='Вид блюда'),
            preserve_default=False,
        ),
    ]
