# Generated by Django 5.0.1 on 2024-02-05 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='carbs',
            field=models.FloatField(default=1, verbose_name='Углеводы'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.TextField(default=' ', verbose_name='Описание продукта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fats',
            field=models.FloatField(default=1, verbose_name='Жиры'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='halal',
            field=models.BooleanField(default=1, verbose_name='Халяль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(default=1, verbose_name='Белки'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vegan',
            field=models.BooleanField(default=1, verbose_name='Вегетарианская'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RequestIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Имя ингредиента')),
                ('description', models.TextField(verbose_name='Описание продукта')),
                ('image', models.ImageField(upload_to='static/images/%Y/%m/%d/', verbose_name='Картинка ингредиента')),
                ('carbs', models.FloatField(default=1, verbose_name='Углеводы')),
                ('fats', models.FloatField(default=1, verbose_name='Жиры')),
                ('protein', models.FloatField(default=1, verbose_name='Белки')),
                ('vegan', models.BooleanField(verbose_name='Вегетарианская')),
                ('halal', models.BooleanField(verbose_name='Халяль')),
                ('is_active', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Заявка в ингредиенты',
                'verbose_name_plural': 'Заявки в ингредиенты',
            },
        ),
    ]
