# Generated by Django 5.0.1 on 2024-02-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_ingredient_carbs_ingredient_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestingredient',
            name='calories',
            field=models.PositiveIntegerField(default=1, verbose_name='Калорийность'),
        ),
    ]
