# Generated by Django 5.0.1 on 2024-02-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_requestingredient_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Имя ингредиента'),
        ),
        migrations.AlterField(
            model_name='requestingredient',
            name='calories',
            field=models.FloatField(default=1, verbose_name='Калорийность'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['title'], name='cooking_rec_title_680f94_idx'),
        ),
    ]
