# Generated by Django 5.0.1 on 2024-02-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='halal',
            field=models.BooleanField(default=True, verbose_name='Халяль'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vegan',
            field=models.BooleanField(default=True, verbose_name='Вегатарианское'),
        ),
    ]
