# Generated by Django 5.0.1 on 2024-02-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0004_alter_ingredient_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestingredient',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
